# SPDX-FileCopyrightText: 2026 Bergruebe
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Beszel hub installation tasks
  when: beszel_hub_enabled | bool
  tags:
    - setup-all
    - setup-beszel-hub
    - install-all
    - install-beszel-hub
  block:
    - name: Validate Beszel hub configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Beszel hub
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Beszel hub uninstallation tasks
  when: not beszel_hub_enabled | bool
  tags:
    - setup-all
    - setup-beszel-hub
  block:
    - name: Uninstall Beszel hub
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
