# SPDX-FileCopyrightText: 2026 Bergruebe
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Beszel hub systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ beszel_hub_identifier }}.service"
  register: beszel_hub_service_stat

- name: Uninstall Beszel hub systemd services and files
  when: beszel_hub_service_stat.stat.exists | bool
  block:
    - name: Ensure Beszel hub systemd service is stopped
      ansible.builtin.service:
        name: "{{ beszel_hub_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Beszel hub systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ beszel_hub_identifier }}.service"
        state: absent

    - name: Ensure Beszel hub support files do not exist
      ansible.builtin.file:
        path: "{{ beszel_hub_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Beszel hub socket path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ beszel_hub_socket_path }}"
      register: beszel_hub_socket_path_deletion_result
      changed_when: beszel_hub_socket_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Beszel hub local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ beszel_hub_data_path }}"
      register: beszel_hub_data_path_deletion_result
      changed_when: beszel_hub_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Beszel hub base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ beszel_hub_base_path }}"
      register: beszel_hub_base_path_deletion_result
      changed_when: beszel_hub_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Beszel hub container network does not exist
      when: beszel_hub_container_network_deletion_enabled
      block:
        - name: Ensure Beszel hub container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ beszel_hub_container_network }}"
            state: absent
          register: beszel_hub_network_deletion_result

        - name: Ensure Beszel hub container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ beszel_hub_container_network }}
          register: beszel_hub_network_deletion_result
          changed_when: beszel_hub_container_network in beszel_hub_network_deletion_result.stdout

- name: Check existence of Beszel hub local data path
  ansible.builtin.stat:
    path: "{{ beszel_hub_data_path }}"
  register: beszel_hub_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Beszel hub local data path
  when: beszel_hub_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Beszel hub has been removed, some old data remains in `" + beszel_hub_data_path + "`. Feel free to delete it."
        ]
      }}
